[2024-12-03T13:15:43.207+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-03T13:15:43.251+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_process_dag.calculate_top_products manual__2024-12-03T13:15:35.226037+00:00 [queued]>
[2024-12-03T13:15:43.266+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_process_dag.calculate_top_products manual__2024-12-03T13:15:35.226037+00:00 [queued]>
[2024-12-03T13:15:43.266+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-12-03T13:15:43.287+0000] {taskinstance.py:2327} INFO - Executing <Task(PostgresOperator): calculate_top_products> on 2024-12-03 13:15:35.226037+00:00
[2024-12-03T13:15:43.296+0000] {standard_task_runner.py:63} INFO - Started process 5080 to run task
[2024-12-03T13:15:43.301+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_process_dag', 'calculate_top_products', 'manual__2024-12-03T13:15:35.226037+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/etl_sales.py', '--cfg-path', '/tmp/tmpfmj_bh4i']
[2024-12-03T13:15:43.305+0000] {standard_task_runner.py:91} INFO - Job 95: Subtask calculate_top_products
[2024-12-03T13:15:43.368+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_process_dag.calculate_top_products manual__2024-12-03T13:15:35.226037+00:00 [running]> on host a6f8f8b1d92d
[2024-12-03T13:15:43.756+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='k.norasit' AIRFLOW_CTX_DAG_ID='etl_process_dag' AIRFLOW_CTX_TASK_ID='calculate_top_products' AIRFLOW_CTX_EXECUTION_DATE='2024-12-03T13:15:35.226037+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-03T13:15:35.226037+00:00'
[2024-12-03T13:15:43.759+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-03T13:15:43.780+0000] {sql.py:276} INFO - Executing: 
        INSERT INTO top_products_in_Chiangmai (order_date, rank_num, product_id, total_sales, total_quantity)
        SELECT order_date, RANK() OVER (PARTITION BY order_date ORDER BY SUM(quantity * amount) DESC) AS rank_num,
               product_id, SUM(quantity * amount), SUM(quantity)
        FROM transaction t
        JOIN user_info ui ON t.user_id = ui.user_id
        WHERE ui.location = 'Chiangmai'
        GROUP BY order_date, product_id
        HAVING rank_num <= 20;
        
[2024-12-03T13:15:43.796+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-12-03T13:15:43.810+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-12-03T13:15:43.838+0000] {sql.py:457} INFO - Running statement: 
        INSERT INTO top_products_in_Chiangmai (order_date, rank_num, product_id, total_sales, total_quantity)
        SELECT order_date, RANK() OVER (PARTITION BY order_date ORDER BY SUM(quantity * amount) DESC) AS rank_num,
               product_id, SUM(quantity * amount), SUM(quantity)
        FROM transaction t
        JOIN user_info ui ON t.user_id = ui.user_id
        WHERE ui.location = 'Chiangmai'
        GROUP BY order_date, product_id
        HAVING rank_num <= 20;
        , parameters: None
[2024-12-03T13:15:43.843+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-03T13:15:43.844+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 404, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 462, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFunction: operator does not exist: text = bigint
LINE 6:         JOIN user_info ui ON t.user_id = ui.user_id
                                               ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

[2024-12-03T13:15:43.862+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl_process_dag, task_id=calculate_top_products, execution_date=20241203T131535, start_date=20241203T131543, end_date=20241203T131543
[2024-12-03T13:15:43.903+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 95 for task calculate_top_products (operator does not exist: text = bigint
LINE 6:         JOIN user_info ui ON t.user_id = ui.user_id
                                               ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
; 5080)
[2024-12-03T13:15:43.961+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-03T13:15:43.994+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T13:15:43.997+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
